config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :animals
end

app/models/animal.rb
#coding: UTF-8

class Animal < ActiveRecord::Base
  before_create :zero_friends

  # :name, :age, :color
  validates :name, presence: true

  scope :old, ->{where("age>10")}

  has_many :foods
  
  belongs_to :user

  protected
    def zero_friends
      self.friends=0
    end
end

app/models/food.rb
#coding: UTF-8

class Food < ActiveRecord::Base
  belongs_to :animal
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :validatable
end

app/controllers/animals_controller.rb
#coding: UTF-8

class AnimalsController < ApplicationController

  def index
    @animals=Animal.all
  end

  def show
    @animal=Animal.find(params[:id])
  end

  def destroy
    @animal=Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path, alert: "Usunięto"
  end

  def new
    @animal=Animal.new
  end

  def create
    @animal=Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path, notice: "Utworzono"
    else
      render 'new'
    end
  end

  def edit
    @animal=Animal.find(params[:id])
  end

  def update
    @animal=Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path, notice: "Edytowano"
    else
      render 'edit'
    end
  end

  private
    def animal_params
      params.require(:animal).permit(:name, :age, :color)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
#coding: UTF-8

class HomeController < ApplicationController
  def index
    @zmienna="Test"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/edit.html.erb
<h1> Edytuj zwierza </h1>

<%= form_for(@animal) do |f| %>
  <% @animal.errors.full_messages.each do |err| %> 
    <li><%= err %></li> 
  <% end %>
  <%= f.label "Imie zwierzaka" %>
  <%= f.text_field :name %>
  <%= f.submit "Zapis mnie" %>
<% end %>

app/views/animals/index.html.haml
%h1 Lista zwierząt
%ul
  -@animals.each do |animal|
    %li
      =animal.name
      =link_to "Pokaż", animal_path(animal.id)

app/views/animals/new.html.erb
<h1> Dodaj zwierza </h1>

<%= form_for(@animal) do |f| %>
  <% @animal.errors.full_messages.each do |err| %> 
    <li><%= err %></li> 
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Zapis mnie" %>
<% end %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>
<%= link_to "Usuń", animal_path(@animal.id), method: :delete %>

app/views/home/index.html.erb
<% if current_user %>
  <h1>Cześć <%= current_user.email %></h1>
  <%= link_to "wyloguj sie", destroy_user_session_path, method: :delete %>
<% else %>
  <h1>Cześć nieznajomy</h1>
  <%= link_to "zarejestruj sie!", new_user_registration_path %>
  <%= link_to "zaloguj sie!", new_user_session_path %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Training
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div
      - if alert
        %p
          Uwaga: #{alert}
      - elsif notice
        %p
          Spokojnie: #{notice}
    = yield